spring.application.name=customer

spring.datasource.url=jdbc:postgresql://localhost:5432/customer_db
spring.datasource.username=postgres
spring.datasource.password=132354Ar
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=mySuperSecretKeyForJwtGeneration2026SpringBootApplication
jwt.expiration=86400000

spring.cache.type=caffeine

spring.artemis.mode=embedded
spring.artemis.embedded.enabled=true
spring.artemis.embedded.persistent=false
spring.artemis.embedded.queues=email.queue,report.queue
spring.artemis.embedded.topics=customer.events.topic

app.queue.email=email.queue
app.queue.report=report.queue
app.topic.customer-events=customer.events.topic